improvement

diff --git a/s2i/bin/assemble b/s2i/bin/assemble
--- a/s2i/bin/assemble
+++ b/s2i/bin/assemble
@@ -1,4 +1,54 @@
-#!/bin/sh
+#!/bin/bash
+set -o pipefail
+IFS=$'\n\t'
 
-cd /tmp/src                  #place where OpenShift puts your source-code (git checkout)
-ansible-container build
+DOCKER_SOCKET=/var/run/docker.sock
+
+if [ ! -e "${DOCKER_SOCKET}" ]; then
+  echo "Docker socket missing at ${DOCKER_SOCKET}"
+  exit 1
+fi
+
+if [ -n "${OUTPUT_IMAGE}" ]; then
+  TAG="${OUTPUT_REGISTRY}/${OUTPUT_IMAGE}"
+fi
+
+if [[ "${SOURCE_REPOSITORY}" != "git://"* ]] && [[ "${SOURCE_REPOSITORY}" != "git@"* ]]; then
+  URL="${SOURCE_REPOSITORY}"
+  if [[ "${URL}" != "http://"* ]] && [[ "${URL}" != "https://"* ]]; then
+    URL="https://${URL}"
+  fi
+  curl --head --silent --fail --location --max-time 16 $URL > /dev/null
+  if [ $? != 0 ]; then
+    echo "Could not access source url: ${SOURCE_REPOSITORY}"
+    exit 1
+  fi
+fi
+
+if [ -n "${SOURCE_REF}" ]; then
+  BUILD_DIR=$(mktemp --directory)
+  git clone --recursive "${SOURCE_REPOSITORY}" "${BUILD_DIR}"
+  if [ $? != 0 ]; then
+    echo "Error trying to fetch git source: ${SOURCE_REPOSITORY}"
+    exit 1
+  fi
+  pushd "${BUILD_DIR}"
+  git checkout "${SOURCE_REF}"
+  if [ $? != 0 ]; then
+    echo "Error trying to checkout branch: ${SOURCE_REF}"
+    exit 1
+  fi
+  popd
+  ansible-container build
+else
+  ansible-container build
+fi
+
+if [[ -d /var/run/secrets/openshift.io/push ]] && [[ ! -e /root/.dockercfg ]]; then
+  cp /var/run/secrets/openshift.io/push/.dockercfg /root/.dockercfg
+fi
+
+if [ -n "${OUTPUT_IMAGE}" ] || [ -s "/root/.dockercfg" ]; then
+  ansible-container shipit #"${TAG}"
+fi
+
